# fly.toml app configuration file generated for walk-visualization-backend on 2024-10-23T14:28:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'walk-visualization-backend'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
 

[[services.ports]]
  handlers = ["tls", "http"]
  port = 4000
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 3000
  protocol = "tcp"
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "3000"

  [[services.ports]]
    handlers = ["http"]
    port = "4000"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000